services:
  backend:
    build: .
    container_name: vertex-backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/${DB_NAME}
      - SPRING_DATASOURCE_USERNAME=${DB_USER}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}

      #JWT Configuration
      - APPLICATION_SECURITY_JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - APPLICATION_SECURITY_JWT_EXPIRATION=86400000 
      - APPLICATION_SECURITY_JWT_REFRESH_TOKEN_EXPIRATION=604800000 

      #MailTrap Configuration
      - MAILTRAP_TOKEN=${MAILTRAP_TOKEN}
      - MAILTRAP_SANDBOX=${MAILTRAP_SANDBOX:-true}
      - MAILTRAP_INBOX_ID=${MAILTRAP_INBOX_ID}
      - APPLICATION_FRONTEND_URL=${FRONTEND_URL}

      #Redis Configuration
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_USER=${REDIS_USER}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
    networks:
      - vertex-network

  postgres:
    image: postgres:16-alpine
    container_name: vertex-db
    restart: always
    stop_grace_period: 1m
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - vertex-network

  redis:
    image: redis:7-alpine
    container_name: vertex-cache
    restart: always
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes"] # Ensures data persistence
    networks:
      - vertex-network

networks:
  vertex-network:
    driver: bridge

volumes:
  postgres_data: