spring.application.name=vertex_backend

spring.config.import=optional:file:.env[.properties]
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/vertex_db}
spring.datasource.username=${DB_USER:dev_user}
spring.datasource.password=${DB_PASSWORD:vertexSecretPassword555}

spring.jpa.hibernate.ddl-auto=update

application.security.jwt.secret-key=${JWT_SECRET_KEY:404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970}
application.security.jwt.expiration=${JWT_EXPIRATION:86400000}
